steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
  - build
  - 'gcr.io/coral-hull-457822-d5/github.com/moeabdelaziz007/amrikyy-aios:$COMMIT_SHA'
  - '--builder=gcr.io/buildpacks/builder:v1'
images:
- 'gcr.io/coral-hull-457822-d5/github.com/moeabdelaziz007/amrikyy-aios:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
