steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/coral-hull-457822-d5/github.com/moeabdelaziz007/amrikyy-aios:$COMMIT_SHA', '.' ]
images:
- 'gcr.io/coral-hull-457822-d5/github.com/moeabdelaziz007/amrikyy-aios:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
