// A "Skill" is a discrete capability the AI system can have.
import React from 'react';
/**
 * Represents the unique identifier for a specific skill an AI system can possess.
 */
export type SkillID =
  'gemini-pro-text' | 'image-generation' | 'video-generation' | 'web-search' |
  'maps-search' | 'flight-search' | 'youtube-search' | 'fast-text' | 'text-to-speech' | 'music-generation' | 'text-translation' | 'live-translation';

/**
 * Categorizes a skill for easier management and understanding.
 */
export type SkillCategory = 'Language' | 'Vision' | 'Audio' | 'Logic' | 'Knowledge';

/**
 * Defines the structure of an AI skill, including its ID, name, description, category, and an icon.
 */
export interface Skill {
  id: SkillID;
  name: string;
  description: string;
  category: SkillCategory;
  icon: React.FC<{className: string}>;
}

/**
 * Represents the unique identifier for each application available in the OS.
 */
export enum AppID { 
  chat = 'chat',
  terminal = 'terminal',
  files = 'files',
  settings = 'settings', 
  luna = 'luna',
  karim = 'karim',
  scout = 'scout',
  maya = 'maya',
  jules = 'jules',
  voice = 'voice',
  workflow = 'workflow',
  travelAgent = 'travelAgent',
  creatorPipeline = 'creatorPipeline',
  nexusPortal = 'nexusPortal',
  marketing = 'marketing',
  travelPlanViewer = 'travelPlanViewer',
  search = 'search',
  maps = 'maps',
  transcriber = 'transcriber',
  videoAnalyzer = 'videoAnalyzer',
  image = 'image',
  audio = 'audio',
  video = 'video',
  smartwatch = 'smartwatch',
  workspace = 'workspace',
  eventLog = 'eventLog',
  skillForge = 'skillForge',
  chronoVault = 'chronoVault',
  creatorStudio = 'creatorStudio',
  cognitoBrowser = 'cognitoBrowser',
  analyticsHub = 'analyticsHub',
  agentForge = 'agentForge',
  avatarStudio = 'avatarStudio',
  agentProfile = 'agentProfile',
  store = 'store',
  notificationCenter = 'notificationCenter',
  liveConversation = 'liveConversation',
  imageAnalyzer = 'imageAnalyzer',
  devToolkit = 'devToolkit',
  agora = 'agora',
  nexusChat = 'nexusChat', 
  devConsole = 'devConsole',
  apiDocs = 'apiDocs',
  growthHub = 'growthHub',
  resourceHub = 'resourceHub',
  geminiAiNews = 'geminiAiNews',
  controlPanel = 'controlPanel', 
  atlasFinance = 'atlasFinance',
  cognitiveCanvas = 'cognitiveCanvas',
  veridianId = 'veridianId',
  translateHub = 'translateHub',
  nexusGo = 'nexusGo',
  nexusFeed = 'nexusFeed',
  nexusProfile = 'nexusProfile',
  travelServices = 'travelServices',
  docsViewer = 'docsViewer',
  atlas = 'atlas',
  cortex = 'cortex',
  orion = 'orion',
  helios = 'helios',
  leo = 'leo',
  zara = 'zara',
  rex = 'rex',
  clio = 'clio',
  pricing = 'pricing',
  gmail = 'gmail',
  youtube = 'youtube',
  weather = 'weather',
  tripPlanner = 'tripPlanner',
  agentsDashboard = 'agentsDashboard',
  nanoBanana = 'nanoBanana',
  veo = 'veo',
}

/**
 * Represents a detailed travel plan generated by an AI.
 */
export interface TravelPlan {
  destination: string;
  tripTitle: string;
  itinerary: {
    day: number;
    title: string;
    activities: string[];
  }[];
  budget: {
    category: string;
    cost: number;
  }[];
  dealsAndLinks: {
    title: string;
    url: string;
  }[];
}

/**
 * Defines the properties of an individual application window instance.
 */
export interface WindowInstance {
  id: number;
  appId: AppID;
  title: string;
  x: number;
  y: number;
  width: number;
  height: number;
  zIndex: number;
  isMinimized: boolean;
  appProps: any;
}

/**
 * Represents a message in a chat conversation, indicating sender, text, and optional sources.
 */
export interface Message {
  id: string;
  sender: 'user' | 'ai' | 'system';
  text: string;
  sources?: {title: string, uri: string}[];
}

/**
 * Represents the unique identifier for an AI agent.
 */
export type AgentID = 'luna' | 'karim' | 'scout' | 'maya' | 'jules' | 
 'leo' | 'zara' | 'rex' | 'clio' |
 'echo' | string;

/**
 * Defines the core properties of an AI agent within the OS.
 */
export interface Agent {
  id: AgentID;
  name: string;
  role: string;
  icon: string; // Emoji representing the agent
  tasks: number; // Number of tasks currently being handled or completed by the agent
  color: string; // Tailwind gradient class or similar for visual representation
  hologram: {
    color: string; // Text color for the hologram effect
    glow: string; // Hex color for the glow effect
    task: string; // Current task description for the hologram
    aberrationColors: [string, string]; // Two hex colors for chromatic aberration effect
  };
  skillIDs: SkillID[]; // List of skills the agent possesses
}

/**
 * Represents a custom AI agent created by the user.
 */
export interface CustomAgent {
    id: AgentID;
    name: string;
    role: string;
    icon: string; // emoji
    avatarVisual?: string; // Optional image URL for avatar, e.g., 'avatar-bot-1'
    voice?: string; // Optional voice ID for speech
    skillIDs: SkillID[];
}

/**
 * Represents an AI agent available from the community marketplace.
 * Extends `CustomAgent` with marketplace-specific details.
 */
export interface CommunityAgent extends CustomAgent {
    description: string;
    author: string;
    rating: number; // e.g., 4.8
    category: 'Productivity' | 'Creative' | 'System' | 'Utility';
    price?: number; // Optional price in AI credits
}

/**
 * Defines the structure of a notification displayed in the OS.
 */
export interface Notification {
    id: number;
    message: string;
    type: 'success' | 'info' | 'error' | 'system';
    category: 'System' | 'Agent' | 'App';
    cta?: { label: string; }; // Optional call-to-action button properties
    onClick?: () => void; // Optional callback for when the notification is clicked
}


/**
 * Represents an entry in the system's event log, detailing agent communication or actions.
 */
export interface LogEntry {
    id: number;
    timestamp: string;
    from: AgentID;
    to?: AgentID;
    message: string;
    type?: 'insight' | 'proactive-offer' | 'standard'; // Added new field for log entry type
}

/**
 * Represents a step in the execution log of a dynamic workflow.
 */
export interface ExecutionLogEntry {
    step: number;
    thought: string;
    action: string;
    result: string;
}

/**
 * Represents an Engram (memory unit) in the Quantum Reasoning Engine.
 */
export interface Engram {
    id: string;
    label: string;
    type: 'travel_plan' | 'conversation' | 'seo_strategy' | 'user_preference' | 'synthesized_insight' | 'project_creation' | 'campaign_launch';
    content: string; // A summary of the memory
    timestamp: number;
    color: string; // Hex color for visual representation
    potentiality?: number; // 0 = superposition, 1 = collapsed/stable
    authorAgentId?: AgentID; // The agent that created this engram
}

/**
 * Represents a connection between two Engrams, indicating a relationship.
 */
export interface EngramConnection {
    from: string; // engram id
    to: string; // engram id
}

/**
 * Represents a temporary reasoning path visualized between Engrams.
 */
export interface ReasoningPath {
    from: string; // engram id
    to: string; // engram id
}

/**
 * Represents a sub-agent used within a larger workflow or system.
 */
export interface SubAgent {
  name: string;
  icon: React.FC<{className: string}>;
}

/**
 * Defines the available visual themes for the OS.
 */
export type Theme = 'obsidian' | 'neon-noir' | 'synthwave-sunset' | 'deep-space' | 'zen' | 'playful' | 'professional';
/**
 * Defines the available wallpaper options.
 */
export type WallpaperID = '/wallpaper.svg' | '/wallpaper2.svg' | '/wallpaper3.svg' | '/wallpaper-obsidian.svg' | 'cityscape-night.jpg' | 'quantum-cascade.jpg' | 'topological-grid.jpg';
/**
 * Defines the available styles for the taskbar.
 */
export type TaskbarTheme = 'glass' | 'solid' | 'transparent';
/**
 * Defines the available visual styles for application windows.
 */
export type WindowStyle = 'gemini' | 'macos' | 'futuristic' | 'cyberpunk';
/**
 * Represents the system voice ID used for text-to-speech.
 */
export type SystemVoice = string;
/**
 * Defines the available dashboard layout presets.
 */
export type DashboardLayout = 'default' | 'work' | 'developer';
/**
 * Defines the possible actions for a voice command.
 */
export type VoiceCommandAction = 'open' | 'close';
/**
 * Represents a structured voice command.
 */
export interface VoiceCommand {
  action: VoiceCommandAction;
  target: AppID | 'all';
}


/**
 * Defines the customizable settings for the entire operating system.
 */
export interface Settings {
  theme: Theme;
  wallpaper: WallpaperID | string;
  accentColor: string;
  taskbarTheme: TaskbarTheme;
  windowStyle: WindowStyle;
  voice: SystemVoice;
  speechRate: number;
  speechPitch: number;
  dashboardLayout: DashboardLayout;
  language: 'en' | 'ar';
}

/**
 * Defines the types of credit transactions a user can have.
 */
export type CreditTransactionType = 'purchase' | 'deposit' | 'bonus' | 'withdrawal' | 'boost' | 'refund';

/**
 * Represents a single credit transaction in the user's history.
 */
export interface CreditTransaction {
    id: string;
    type: CreditTransactionType;
    amount: number; // Positive for deposit/bonus/refund, negative for withdrawal/boost/purchase
    timestamp: string; // ISO string
    description: string;
}

/**
 * Props interface for the Settings application.
 */
export interface SettingsAppProps {
  settings: Settings;
  onSettingsChange: (newSettings: Partial<Settings>) => void;
  resetSettings: () => void;
  userAccount: UserAccount;
  onUserAccountChange: (newAccount: Partial<UserAccount>) => void;
  paymentMethods: PaymentMethod[];
  onAddPaymentMethod: (method: PaymentMethod) => void;
  onUpgrade: () => void;
  creditTransactions: CreditTransaction[];
}

/**
 * Represents a trending item in a list.
 */
export interface TrendingItem {
  rank: number;
  name: string;
  category: 'Tool' | 'Model' | 'News';
  change: number;
}

/**
 * Defines a node within a workflow, representing a step assigned to an agent.
 */
export interface WorkflowNode {
    id: string;
    agentId: AgentID;
    description: string;
}

/**
 * Defines a connection between two nodes in a workflow.
 */
export interface WorkflowConnection {
    from: string;
    to: string;
}

/**
 * Represents a complete AI-driven workflow.
 */
export interface Workflow {
    title: string;
    nodes: WorkflowNode[];
    connections: WorkflowConnection[];
}

/**
 * Represents an alarm setting in the Smart Watch app.
 */
export interface Alarm {
  id: string;
  time: string;
  label: string;
  enabled: boolean;
}

/**
 * Represents an automation rule in the Smart Watch app.
 */
export interface Automation {
  id: string;
  trigger: string;
  action: {
    appId: AppID;
    task: string;
  };
}

/**
 * Represents a generic user profile.
 */
export interface User {
  id: string;
  name: string;
  avatarUrl: string;
}

/**
 * Represents a collaborative workspace with various tabs and members.
 */
export interface Workspace {
  id: string;
  title: string;
  activeTab: 'notes' | 'music' | 'youtube' | 'whiteboard';
  notes?: string;
  youtubeUrl?: string;
  musicPlaylist?: { title: string; artist: string; }[];
  members: User[];
}

/**
 * Represents a project managed in the Creator Studio.
 */
export interface Project {
    id: string;
    name: string;
    description: string;
    status: 'Active' | 'Paused' | 'Completed';
    earnings: number;
}

/**
 * Represents a task associated with a project or stand-alone.
 */
export interface Task {
    id: string;
    text: string;
    completed: boolean;
    projectId?: string;
    createdAt: string; // ISO string
    dueDate?: string; // ISO string (YYYY-MM-DD)
    priority: 'Low' | 'Medium' | 'High';
}

/**
 * Represents a core system entity (e.g., an app or an agent) with its description and workflow.
 */
export interface SystemEntity {
  id: AppID | AgentID;
  name: string;
  icon: string; // Material Symbols icon name
  goal: string;
  description: string;
  workflow: {
    icon: string; // Material Symbols icon name
    label: string;
  }[];
}

/**
 * Represents data for a cryptocurrency.
 */
export interface CryptoData {
    id: string;
    name: string;
    ticker: string;
    icon: string;
    price: number;
    change: number;
    history: number[];
}

/**
 * Represents the user's account details within the OS.
 */
export interface UserAccount {
    osId: string; // Unique OS identifier for the user
    name: string;
    avatar: string; // Emoji or URL
    tier: 'Free' | 'Pro';
    aiCredits: number;
    referralCode?: string;
    referralsCount?: number;
    creditsEarnedFromReferrals?: number;
    creatorScore?: number;
    joinDate: string; // Date when the user joined the OS (ISO string)
    trustScore: number; // Dynamic score based on activity and adherence to guidelines
}

/**
 * Represents a logged action performed by the user within an application.
 */
export interface UserAction {
    appId: AppID;
    timestamp: number;
    details?: Record<string, any>; // Additional context about the action
}

/**
 * Represents data for a visualization component (e.g., a chart or summary).
 */
export interface VisualizationData {
    type: 'bar' | 'pie' | 'summary';
    title: string;
    data: any; // Can be ChartData or a string for summary
}

/**
 * Represents data specifically for a chart visualization.
 */
export interface ChartData {
    labels: string[];
    datasets: {
        label: string;
        data: number[];
        backgroundColor: string[];
    }[];
}

/**
 * Represents an available voice option for text-to-speech.
 */
export interface VoiceOption {
    id: string;
    name: string;
    language: string;
    accent: string;
    gender: 'Male' | 'Female';
}

/**
 * Represents a calendar event fetched from an integrated service.
 */
export interface CalendarEvent {
  id: string;
  summary: string;
  start: string; // ISO string for datetime
  end: string;   // ISO string for datetime
}

/**
 * Represents a file from an integrated drive service.
 */
export interface DriveFile {
  id: string;
  name: string;
  link: string;
}

/**
 * Represents an email message snippet from an integrated mail service.
 */
export interface GmailMessage {
  id: string;
  snippet: string;
}

/**
 * Represents content prepared for sharing across social platforms or within the OS.
 */
export interface SharedContent {
    type: 'project' | 'travel_plan' | 'image' | 'video' | 'text'; // Added 'text' for generic posts
    title: string;
    subtitle: string;
    cta: string; // Call to action
    imageUrl?: string; // Optional URL for image content
}

/**
 * Represents the details for a social media post, including caption and hashtags.
 */
export interface SocialPost {
    caption: string;
    hashtags: string[];
}

/**
 * Represents a comment on a Nexus social post.
 */
export interface NexusComment {
    id: string;
    authorName: string;
    osId: string;
    text: string;
    timestamp: number; // Unix timestamp
}

/**
 * Represents a post on the Nexus social feed.
 */
export interface NexusPost {
    id: string;
    author: string; // User's display name
    osId: string; // User's OS ID
    content: SharedContent;
    socialPost: SocialPost;
    likes: number;
    views: number;
    comments: NexusComment[];
    boosted?: boolean;
}

/**
 * Represents an item listed on the Agora Marketplace.
 */
export interface AgoraListing {
    id: string;
    type: 'agent' | 'workflow';
    asset: CustomAgent | Workflow; // The actual asset being listed
    author: string;
    price: number; // Price in AI Credits
    description: string;
}

/**
 * Represents a live chat message in a real-time conversation.
 */
export interface LiveChatMessage {
    id: string;
    user: { id: string; name: string; avatar: string; };
    text: string;
    timestamp: number;
}

/**
 * Represents a user's payment method.
 */
export interface PaymentMethod {
    id: string;
    type: 'paypal' | 'stripe' | 'googlepay';
    identifier: string; // e.g., email for paypal, last 4 digits for card
}

/**
 * Represents a bounty or task offered in the Growth Hub for creators.
 */
export interface CreatorBounty {
    id: string;
    title: string;
    description: string;
    creditReward: number;
    action: {
        type: 'open_app' | 'create_agent' | 'share_content';
        appId?: AppID;
        contentType?: SharedContent['type'];
    };
}

/**
 * Represents an item in the Resource Hub.
 */
export interface ResourceItem {
    id: string;
    title: string;
    description: string;
    url: string;
    category: 'AI/ML' | 'Frontend' | 'Developer Tools' | 'Design';
    tags: string[];
}

/**
 * Defines possible weather conditions.
 */
export type WeatherCondition = 'Sunny' | 'Partly Cloudy' | 'Cloudy' | 'Rainy' | 'Stormy' | 'Clear';

/**
 * Represents current weather data for a location.
 */
export interface CurrentWeather {
    location: string;
    temp: number; // Temperature in Celsius
    condition: WeatherCondition;
    icon: string; // Material Symbols icon name
    high: number; // High temperature for the day
    low: number; // Low temperature for the day
}

/**
 * Represents a single day's forecast.
 */
export interface ForecastDay {
    day: string; // e.g., 'Mon', 'Tue'
    high: number;
    low: number;
    icon: string; // Material Symbols icon name
    condition: WeatherCondition;
}

/**
 * Represents complete weather data including current and forecast.
 */
export interface WeatherData {
    current: CurrentWeather;
    forecast: ForecastDay[];
}

/**
 * Represents a delivery option (e.g., from a restaurant).
 */
export interface DeliveryOption {
    name: string;
    description: string;
    deliveryTime: string;
    priceRange: string;
    rating: number;
    cuisine?: string;
    tags: string[];
    url: string;
    isTrending?: boolean; // New: For smart delivery
}

/**
 * Represents a fast food restaurant recommendation.
 */
export interface FastFoodRestaurant {
    name: string;
    cuisine: string;
    rating: number;
    deliveryTime: string;
    priceLevel: '$' | '$$' | '$$$' | '$$$$';
    isTrending: boolean;
    imageUrl: string;
    address: string;
    website: string;
    reason: string; // AI-generated reason for recommendation
}

/**
 * Represents a ride-sharing option.
 */
export interface RideOption {
    service: string;
    estimatedCost: string;
    estimatedTime: string;
    currency: string;
    surgePricing: boolean;
    eta?: string; // Estimated time of arrival
    providerLogo?: string; // Logo for the ride service (e.g., Uber, Lyft)
}

/**
 * Represents a cleaning service recommendation.
 */
export interface CleaningService {
    name: string;
    type: string; // e.g., "Deep Clean", "Standard Clean"
    priceRange: string;
    rating: number;
    availability: string; // e.g., "Next Day", "Same Week"
    contact: string; // e.g., phone number or website
    imageUrl?: string;
    reason: string; // AI-generated reason for recommendation
}

/**
 * Represents a nightlife event or venue recommendation.
 */
export interface NightlifeEvent {
    name: string;
    type: string; // e.g., "Nightclub", "Bar", "Live Music", "VIP Event"
    description: string;
    location: string;
    date: string;
    time: string;
    ticketsUrl?: string;
    vipOptions?: boolean;
    imageUrl?: string;
    reason: string; // AI-generated reason for recommendation
}

/**
 * Defines the health status of an AI agent.
 */
export type AgentHealthStatus = 'Nominal' | 'Warnings' | 'Critical';

/**
 * Represents various metrics for monitoring an AI agent's performance and health.
 */
export interface AgentMetrics {
    currentLoad: number; // Percentage
    uptime: string; // e.g., "2 days, 5 hours"
    recentErrors: number;
    status: AgentHealthStatus;
}

/**
 * Represents a single financial news article.
 */
export interface FinancialNews {
    title: string;
    source: string;
    url: string;
}

/**
 * Represents a detailed financial analysis report.
 */
export interface FinancialAnalysis {
    summary: string;
    bullCase: string;
    bearCase: string;
    keyMetrics: { name: string; value: string }[];
    recentNews: string;
}

/**
 * Represents the details required for a flight search query.
 */
export interface FlightSearchDetails {
    origin: string;
    destination: string;
    departureDate: string; // ISO date string (YYYY-MM-DD)
    returnDate?: string; // Optional for round trip
    passengers: number;
    cabinClass: 'Economy' | 'Premium Economy' | 'Business' | 'First';
}

/**
 * Represents a single flight option found.
 */
export interface FlightOption {
    carrier: string;
    price: number;
    currency: string;
    departureTime: string; // HH:MM
    arrivalTime: string; // HH:MM
    duration: string; // e.g., "5h 30m"
    stops: number;
    url: string; // Booking URL
}